export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";
export const GET_PRODUCTS_FULFILLED = "GET_PRODUCTS_FULFILLED";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const CREATE_PRODUCT_PENDING = "CREATE_PRODUCT_PENDING";
export const CREATE_PRODUCT_FULFILLED = "CREATE_PRODUCT_FULFILLED";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
